### ISSUE TITLE
Please add support for recent versions of c2hs

### ISSUE THREAD

**Issue by peti** [phaazon/al#1]
We upgraded NixOS to c2hs 0.24.1 a while ago, but now it turns out that `al` can't be compiled with that version: http://hydra.cryp.to/build/622015/log/raw. Would it be possible to add support for recent versions of this tool?

**Comment by phaazon** [comment]
Sure! I’ll try that tonight since I won’t be on my computer in the afternoon :)

**Comment by peti** [comment]
BTW, I believe that all there is to it is to relax the upper bound. The package compiles fine when the later version is used.

**Comment by phaazon** [comment]
Sure, then the fix is trivial :)

**Comment by phaazon** [comment]
Done :) I’m uploading on hackage.

**Comment by phaazon** [comment]
@peti, may you try with [this](http://hackage.haskell.org/package/al-0.1.1.3)? :)

**Comment by peti** [comment]
The new version works fine; thank you very much for the quick fix!

**Comment by phaazon** [comment]
\o
