### ISSUE TITLE
Support for c2hs version 0.25.2?

### ISSUE THREAD

**Issue by peti** [phaazon/al#3]
We updated c2hs to the latest version in NixOS, and now `al` won't compile anymore: http://hydra.cryp.to/build/783519/log/raw. Would it be possible to release a new version to Hackage that remedies this issue?

**Comment by phaazon** [comment]
Sure. :) I’m on it!

**Comment by phaazon** [comment]
Done. I’ll keep on eye on the build on hydra. :)

**Comment by phaazon** [comment]
[Since the build has passed](http://hydra.cryp.to/build/785735), I’m closing the issue @peti. Thanks for reporting!
